### ISSUE TITLE
accepts 'add 2021-1-21/winterpark' as well as 'add 2021-01-21/winterpark

### ISSUE THREAD

**Issue by brooksmarka** [jbrennan414/ski-scraper#8]
![Screen Shot 2021-01-20 at 1 16 55 PM](https://user-images.githubusercontent.com/20527972/105230108-21dbca00-5b22-11eb-9b34-1fb0f9d4b7a9.png)

**Comment by jbrennan414** [comment]
yeeeeeesh, great point

**Comment by jbrennan414** [comment]
this should apply to both day and month
